import { test, expect } from '@fixtures/test-context.fixture.js';
import { buildTestData } from '@helpers/index.js';
import { createPreQualifiedApplication, driveLeadToFunding } from '@helpers/api-setup.helpers.js';
import { installPostMessageRecorder, signGowSignInFrame } from '@helpers/gowsign-signing.helper.js';
import { waitForLeadStatus } from '@helpers/esign-db.helpers.js';
import { loginToPortalWithOptions } from '@helpers/auth.helpers.js';
import { navigateToServicingCustomer } from '@helpers/navigation.helpers.js';
import { AlternativeContractModalPage } from '@pages/gowsign/index.js';
import { MissingDataFormPage, TermsOfAgreementPage } from '@pages/origination/index.js';
test.describe('explore servicing', () => {
  test.use({ envName: 'qa2' });
  test('dump sidebar', async ({ page, api, ctx, db, testEnv }, testInfo) => {
    test.setTimeout(720_000);
    const { merchant, applicant } = buildTestData({ env: 'qa2', state: 'CA', merchant: 'TireAgent', orderTotal: '800', orderDescription: 'svc sidebar' });
    await installPostMessageRecorder(page);
    await createPreQualifiedApplication(api, merchant, applicant, ctx, { skipPaymentInfo: true }, testInfo);
    const inv = await api.invoice.sendInvoice(merchant, ctx.leadUuid);
    await page.goto(inv.body?.paymentDetailsList?.[0]?.redirectUrl ?? '');
    const md = new MissingDataFormPage(page); await md.waitForLoaded(15_000);
    await md.fillAndSubmit({ firstName: applicant.firstName, lastName: applicant.lastName, cardNumber: '5500000000000004', cvc: '123', expiration: '12/2030' });
    const tm = new TermsOfAgreementPage(page); await tm.waitForLoaded(30_000); await tm.acceptAndProceedWithProtectionPlan(false);
    const modal = new AlternativeContractModalPage(page); await modal.waitForOpen(30_000);
    const frame = modal.getGowSignFrame(); await frame.locator('body').waitFor({ state: 'visible', timeout: 30_000 });
    const result = await signGowSignInFrame(page, frame, { preauthChoice: 'yes', fontIndex: 0, waitForCompleted: true });
    expect(result.signClicked).toBe(true);
    await waitForLeadStatus(db, ctx.leadPk!, 'SIGNED', { timeoutMs: 60_000 });
    await driveLeadToFunding(api, merchant, ctx);
    const acc = await db.queryOne<{ pk: string }>('SELECT pk FROM uown_sv_account WHERE lead_pk=$1 ORDER BY pk DESC LIMIT 1', [Number(ctx.leadPk)]);
    ctx.accountPk = acc!.pk;
    await loginToPortalWithOptions(page, testEnv.servicingUrl, testEnv);
    await navigateToServicingCustomer(page, String(ctx.accountPk));
    await page.waitForTimeout(2_000);
    console.log('\n=== Sidebar texts ===');
    const sidebar = await page.locator('.sidebar a, .sidebar div, .sidebar button, [class*=sidebar] a, nav a').allInnerTexts().catch(() => []);
    for (const t of [...new Set(sidebar.map(s=>s.trim()).filter(s=>s && s.length<60))]) console.log(`  - "${t}"`);
    console.log('\n=== Top menu items ===');
    const top = await page.locator('[role="menuitem"], button').allInnerTexts().catch(() => []);
    for (const t of [...new Set(top.map(s=>s.trim()).filter(s=>s && s.length<40))]) console.log(`  - "${t}"`);
    await page.screenshot({ path: testInfo.outputPath('svc.png'), fullPage: true });
  });
});
